### ISSUE TITLE
Add and update Readme

### ISSUE THREAD

**Issue by bhuvnesh** [bhuvnesh/Mini-Project-Calculator#1]

**Comment by Abhicoder03** [comment]
Hi I would like to work on this.

**Comment by Abhicoder03** [comment]
Could you tell me more about this project.

**Comment by shikhacodes** [comment]
I would like to contribute

**Comment by atish-90** [comment]
I would like to contribute

**Comment by gaurangisinha** [comment]
Hello, @bhuvnesh I am very keen on contributing to this project. Please tell me what needs to be done. I will be happy to contribute.

**Comment by Sa-kshi** [comment]
I would like to contribute
