### ISSUE TITLE
I am facing issue in pushing a commit 

### ISSUE THREAD

**Issue by Sa-kshi** [bhuvnesh/Mini-Project-Calculator#10]
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/Sa-kshi/Mini-Project-Calculator.git'

**Comment by saiharsha-22** [comment]
@Sa-kshi I have you used the command git add . before pushing

**Comment by Sa-kshi** [comment]
I used git add<name_of_the_file_changes_made>

**Comment by saiharsha-22** [comment]
first use git add .
next git commit -m " "
git push
