### ISSUE TITLE
add colors/styles to the calculator

### ISSUE THREAD

**Issue by bhuvnesh** [bhuvnesh/Mini-Project-Calculator#3]
Note- 
-button colors must be of white color with black/grey font.
- add a gradient background

**Comment by shanmukhkalasamudram** [comment]
I'm Interested to do this, Can you please assign this to me

**Comment by Avninder99** [comment]
i would like to do it, Can i try ?

**Comment by shikhacodes** [comment]
I would like to contribute. I have worked on a similar project before.

**Comment by kratikasinghal** [comment]
can I work on this issue?

**Comment by bhuvnesh** [comment]
> I would like to contribute. I have worked on a similar project before.

I have added the desired font style in the index.html & style.css to be used in this.

**Comment by shikhacodes** [comment]
> 
> 
> > I would like to contribute. I have worked on a similar project before.
> 
> I have added the desired font style in the index.html & style.css to be used in this.

Yes I will use the same
