### ISSUE TITLE
add features

### ISSUE THREAD

**Issue by bhuvnesh** [bhuvnesh/Mini-Project-Calculator#4]

**Comment by kratikasinghal** [comment]
Can I work on this issue?

**Comment by kratikasinghal** [comment]
hi! I have worked on this issue and added some features please assign me so I can add my repository

**Comment by saiharsha-22** [comment]
@bhuvnesh I have done completed the mini-project calculator using Html CSS and javascript and have added a dark mode feature for the website. so shall I pull my request?

**Comment by kratikasinghal** [comment]
Hi! I have added more features and buttons including the scientific terms using html and javascript. Please assign me this issue

**Comment by bhuvnesh** [comment]
> Hi! I have added more features and buttons including the scientific terms using html and javascript. Please assign me this
